version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-app
    ports:
      - "3000:3000"
    restart: always

    nginx:
      image: nginx:latest
      container_name: nginx proxy
      volume:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8080:80"
        - "443:443"
      restart: always
      depends on:









  