name: 'Build and Push Docker Image'

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest
# second job , to deploy the docker compose file
  deploy-to-production:
    needs: build-and-push
    run-on: ubuntu-latest
    environment: production
    concurrency:
        gtoup: production_emvironment
        cancel-in-progress: false
        steps:
          - name:install SSH key
          uses: shimataro/ssh-key-action@v2
          with:
            keys: ${{ secrets.SSH PRIVATE KEY }}
            name: id_rsa
            known_hosts: ${{secrets.SSH KNOWN HOSTS }}
            cofig: |
                hostproduction|
                hostname ${{secrets.PRODUCTION HOST}}
                USER ${{ secrets.production}}
























































































































































